version: "3.9"
services:
  rapidorders:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    networks:
      - backend
    volumes:
      - .:/home/app
      - /home/app/node_modules
    depends_on:
      - mongodev
    environment:
      - NODE_ENV=development
  mongodev:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rapidorders
      - MONGO_INITDB_ROOT_PASSWORD=rapid_orders_backend
    volumes:
      - mongo-data:/data/db
networks:
  backend:
    driver: bridge
volumes:
  mongo-data: