version: "3.9"
services:
  rapidorders:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rapidorders
      - MONGO_INITDB_ROOT_PASSWORD=rapid_orders_backend
    volumes:
      - mongo-data:/data/db
networks:
  backend:
    driver: bridge
volumes:
  mongo-data: