export const usersSeedData = [
  {
    name: "Juan Perez",
    email: "juanperez@example.com",
    password: "password1!a",
    role: "ADMIN_ROLE",
  },
  {
    name: "Maria Rodriguez",
    email: "mariarodriguez@example.com",
    password: "password2!b",
    role: "CHEF_ROLE",
  },
  {
    name: "Carlos Gomez",
    email: "carlosgomez@example.com",
    password: "password3!c",
    role: "WAITER_ROLE",
  },
  {
    name: "Luisa Martinez",
    email: "luisamartinez@example.com",
    password: "password4!d",
    role: "ADMIN_ROLE",
  },
  {
    name: "Javier Hernandez",
    email: "javierhernandez@example.com",
    password: "password5!e",
    role: "CHEF_ROLE",
  },
  {
    name: "Ana Ramirez",
    email: "anaramirez@example.com",
    password: "password6!f",
    role: "WAITER_ROLE",
  },
  {
    name: "Pedro Castillo",
    email: "pedrocastillo@example.com",
    password: "password7!g",
    role: "ADMIN_ROLE",
  },
  {
    name: "Sofia Rodriguez",
    email: "sofiarodriguez@example.com",
    password: "password8!h",
    role: "CHEF_ROLE",
  },
  {
    name: "Mateo Perez",
    email: "mateoperez@example.com",
    password: "password9!i",
    role: "WAITER_ROLE",
  },
  {
    name: "Valentina Gomez",
    email: "valentinagomez@example.com",
    password: "password10!j",
    role: "ADMIN_ROLE",
  },
  {
    name: "Elena Flores",
    email: "elenaflores@example.com",
    password: "password11!k",
    role: "CHEF_ROLE",
  },
  {
    name: "Ricardo Sanchez",
    email: "ricardosanchez@example.com",
    password: "password12!l",
    role: "WAITER_ROLE",
  },
  {
    name: "Juliana Torres",
    email: "julianatorres@example.com",
    password: "password13!m",
    role: "ADMIN_ROLE",
  },
  {
    name: "Gabriel Mendoza",
    email: "gabrielmendoza@example.com",
    password: "password14!n",
    role: "CHEF_ROLE",
  },
  {
    name: "Carmen Silva",
    email: "carmensilva@example.com",
    password: "password15!o",
    role: "WAITER_ROLE",
  },
  {
    name: "Fernando Diaz",
    email: "fernandodiaz@example.com",
    password: "password16!p",
    role: "ADMIN_ROLE",
  },
  {
    name: "Adriana Vargas",
    email: "adrianavargas@example.com",
    password: "password17!q",
    role: "CHEF_ROLE",
  },
  {
    name: "Hugo Romero",
    email: "hugoromero@example.com",
    password: "password18!r",
    role: "WAITER_ROLE",
  },
  {
    name: "Isabel Castro",
    email: "isabelcastro@example.com",
    password: "password19!s",
    role: "ADMIN_ROLE",
  },
  {
    name: "Alejandro Ortega",
    email: "alejandroortega@example.com",
    password: "password20!t",
    role: "CHEF_ROLE",
  },
];
