name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker hub image
      run: |
        docker build -t rapidordersbackend .
        docker tag rapidordersbackend:latest ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest
    - name: Publish image to docker hub
      run: docker push ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from Docker Hub
        run: /usr/bin/docker pull ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest
      - name: Delete old container
        run: docker rm -f rapidordersbackend
      - name: Run container from image
        run: docker run -d -p 8080:8080 --name rapidordersbackend ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest
