name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: ls -l
      - name: Dependencies install
        run: npm install
      - name: Run Lint
        run: npm run eslint
      - name: Run tests
        run: npm run test
      - name: Login to docker hubgit a
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker hub image
        run: |
          docker build -t rapidordersbackend .
          docker tag rapidordersbackend:latest ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.MY_EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest
            sudo docker stop rapidordersbackend || true
            sudo docker rm rapidordersbackend
            sudo docker rapidordersbackend || true
            sudo docker run -d -p 8080:8080 \
            -e PORT=${{ secrets.PORT }} \
            -e MONGO_CONNECTION_URL=${{ secrets.MONGO_CONNECTION_URL }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
            -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
            -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
            --name rapidordersbackend \
            ${{ secrets.DOCKER_REPO_URL }}/rapidordersbackend:latest